import Container from "@/components/layout/Container";
import FlexLayout from "@/components/layout/FlexLayout";
import Button from "@/components/ui/Button";
import FrostCard from "@/components/ui/FrostCard";
import Quote from "@/components/ui/icons/Quote";

const Trial = () => {
  return (
    <div className="py-16 text-white bg-[url(/Banner.png)] bg-cover">
      <Container>
        <div>
          <h2 className="text-[40px] font-bold mb-8 text-center">
            Ready to Grow? Get your FREE Quote Today!
          </h2>

          <FlexLayout justify="justify-center" spaceClass="space-x-10">
            <input
              className="self-stretch p-4 rounded w-[40%] placeholder-[#00000080]"
              type="url"
              placeholder="Enter Your Website"
              required
            ></input>
            <div
              className="bg-transparent"
              style={{ boxShadow: "0 0 15px rgba(255,255,255,0.5)" }}
            >
              <Button>
                <p className="px-4">Get Started</p>
              </Button>
            </div>
          </FlexLayout>

          <div className="mt-16  w-[98%] 2xl:w-[70%] mx-auto">
            <FlexLayout spaceClass="space-x-8">
              <FrostCard>
                <div className="flex flex-col justify-between h-full">
                  <h3 className="text-[35px] font-semibold">
                    Increased Website Traffic by
                  </h3>
                  <h2 className="font-bold text-[50px] my-8">+87%</h2>
                  <div
                    className="bg-transparent w-max mx-auto"
                    style={{ boxShadow: "0 0 20px rgba(255,255,255,1)" }}
                  >
                    <Button
                      bgColorClass="bg-[#4E01A9]"
                      borderColorClass="border-[#4E01A9]"
                    >
                      <p className="px-8">Case Study</p>
                    </Button>
                  </div>
                </div>
              </FrostCard>

              <FrostCard>
                <div className="flex flex-col justify-between h-full">
                  <h3 className="text-[35px] font-semibold">
                    Increased Conversion Rate by
                  </h3>
                  <h2 className="font-bold text-[50px] my-8">+71%</h2>
                  <div
                    className="bg-transparent w-max mx-auto"
                    style={{ boxShadow: "0 0 20px rgba(255,255,255,1)" }}
                  >
                    <Button
                      bgColorClass="bg-[#4E01A9]"
                      borderColorClass="border-[#4E01A9]"
                    >
                      <p className="px-8">Case Study</p>
                    </Button>
                  </div>
                </div>
              </FrostCard>

              <FrostCard>
                <div className="flex flex-col justify-between h-full">
                  <h3 className="text-[35px] font-semibold">
                    Increased Leads Generated by
                  </h3>
                  <h2 className="font-bold text-[50px] my-8">+60%</h2>
                  <div
                    className="bg-transparent w-max mx-auto"
                    style={{ boxShadow: "0 0 20px rgba(255,255,255,1)" }}
                  >
                    <Button
                      bgColorClass="bg-[#4E01A9]"
                      borderColorClass="border-[#4E01A9]"
                    >
                      <p className="px-8">Case Study</p>
                    </Button>
                  </div>
                </div>
              </FrostCard>

              <FrostCard>
                <div className="mt-7 mx-4">
                  <Quote />
                  <p className="text-[20px] font-semibold py-6">
                    Icon Testimonial We measure our success by how much we WOW
                    our clients.
                  </p>
                  <FlexLayout>
                    <div className="ml-4 rounded-[50%] h-[50px] w-[50px] bg-[#D9D9D9]"></div>
                    <div className="leading-none">
                      <h6 className="font-semibold">Bill Craig</h6>
                      <p className="text-[13px] text-[#FFFFFFB2] font-semibold">
                        WEBFX PRESIDENT
                      </p>
                    </div>
                  </FlexLayout>
                </div>
              </FrostCard>
            </FlexLayout>
          </div>
        </div>
      </Container>
    </div>
  );
};

export default Trial;
